@startuml

' Command line interface design

interface SerialCommunication {
    +SendData(data: uint8[], onSent: Function): void
    +ReceiveData(data: uint8[], onReceived: Function): void
}

interface ISerialLineSource {
    +ReceiveLine(onLineReceived: Function): void
}

class SerialIOStream implements ISerialLineSource {
    -serial: SerialCommunication
    +SetInputHandler(handler: Function): void
    +WriteOutput(data: string): void
}

class CommandLineInterface {
    -commands: ICommand[]
    -stream: ISerialLineSource
    +RegisterCommand(command: ICommand): void
    +ProcessInput(input: string): void
}   

interface ICommand {
    +Execute(arguments: string[]): void
    +GetDescription(): string
    +GetName(): string
}

' SerialIOStream has a SerialCommunication
SerialIOStream --> SerialCommunication : has

' CommandLineInterface uses ISerialLineSource
CommandLineInterface --> ISerialLineSource : uses

' CommandLineInterface has multiple ICommand
CommandLineInterface --> ICommand : has



@enduml
